### ISSUE TITLE
approval Translate Swift Education on Spanish 

### ISSUE THREAD

**Issue by Xc0d3dev** [SwiftEducation/SwiftEducation.github.io#13]
Hello I would like to translate and publish resources in Spanish . I need your approval to start the translation and publication .

Thank you.

**Comment by ybakos** [comment]
Hi @Xc0d3dev , that would be great! You don't need my approval - simply fork the [teaching-app-dev-swift](https://github.com/SwiftEducation/teaching-app-dev-swift) repository, use the **spanish** branch, and send a pull request.
