### ISSUE TITLE
Can't download course materials archive

### ISSUE THREAD

**Issue by masonelmore** [SwiftEducation/SwiftEducation.github.io#14]
https://raw.githubusercontent.com/SwiftEducation/SwiftEducation.github.io/master/assets/archives/Teaching%20App%20Development%20with%20Swift.zip 

This link does not return the actual ZIP file, but only some metadata about the file like this:

version https://git-lfs.github.com/spec/v1
oid sha256:5364c2a7e3bee8dab6a4fcd54aab8144906e39ade947c9bb0fb9598b926a0221
size 177993537

I'm not sure if I am doing something wrong or if it is a problem with GutHub.

**Comment by ybakos** [comment]
Thanks for posting the issue. It's because we've reached our download quota - I'm working on getting more.

**Comment by ybakos** [comment]
You should be able to download as expected now.
