### ISSUE TITLE
Outdated?

### ISSUE THREAD

**Issue by JamesNewton** [SwiftEducation/SwiftEducation.github.io#22]
I'm being told

"All these iOS/Swift lessons at this GitHub location (swifteducation.github.io) are too old (Swift 2.x). They can only be opened in Xcode 8.x. PHHS has Xcode 9.4 installed. The latest from Apple is Xcode10 and Swift 4. "

If that is true, could you please update your web site to indicate this is no longer applicable so people won't be spec'ing it for classes when it can't actually be used? Thanks... would have saved us a lot of headaches.

**Comment by ybakos** [comment]
@JamesNewton 👍

**Comment by ybakos** [comment]
Deprecation notices have been added to all repo READMEs and descriptions, as well as the public web site.
